#!/bin/bash

# Creates clone 'env/squeezeReiserfs' if doesn't exists
# Creates deployment 'env/squeezeReiserfs' using the clone  
# Run ITs

# Resolve script location, $0 may be a link
script="$0"
# Need this for relative symlinks
while [ -h "$script" ] ; do
  lst=$(ls -ld "$script")
  lnk=$(expr "$lst" : '.*-> \(.*\)$')
  if expr "$lnk" : '/.*' > /dev/null; then
    script="$lnk"
  else
    script=$(dirname "$script")/"$lnk"
  fi
done
BLSS_HOME=$(dirname "$script")/../..
BIN="$BLSS_HOME"/bin
ENV="$BLSS_HOME"/env
EXT="$BLSS_HOME"/ext
TST="$BLSS_HOME"/tst

[ ! -e /tmp/cloneitroot ] && sudo mkdir /tmp/cloneitroot && $TST/squeezeReiserfs/clone
$TST/squeezeReiserfs/dep && $TST/squeezeReiserfs/it-dep

