#!/bin/bash

# === WELCOME ===
# 
# BLSS stands for Bootstrapped Linux Server Systems, it is set of tools to quickly 
# assemble multiple small & optimized Linux-based virtual appliances with the 
# purpose of an easy deployment of package-based distributed systems, like Apache 
# Hadoop Cloudera Distribution, where every server have a different role in a 
# computational cluster or grid. 
# 
# The delivered virtual appliances fit better for servicing purpose, they are 
# reduced in size and have a small memory footprint. The lifecycle of such systems 
# is composed of three phases: prototyping, where shared packages & configuration 
# is settled; cloning, where different server roles are defined; and finally 
# deployment where unique appliances are produced.
# 
# The project is hosted at https://bitbucket.org/eduardo_lago_aguilar/blss
# 
# === AUTHOR ===
#   Written by Eduardo Lago Aguilar, eduardo.lago.aguilar@gmail.com, 
#   http://eduardo-lago.blogspot.com

# it-clone-debian:
#
#   Common ITs for all Debian-based clones

# Test Case: Test for hostname config
ctx cat /etc/hostname | {
  ln_is "my-debian-clone" "Verify if '/etc/hostname' is correct"
}
ctx cat /etc/hosts | {
  ln_is "127.0.0.1 localhost.localdomain localhost" "Verify if localhost is 127.0.0.1 at /etc/hosts"
  ln_is "127.0.1.1 my-debian-clone my-debian-clone.home.dev" "Verify if my-debian-clone and my-debian-clone.home.dev is 127.0.1.1 at /etc/hosts"
  ln_is_empty  
  ln_is "# The following lines are desirable for IPv6 capable hosts" "Verify if IPv6 capable hosts is commented"
  ln_is "## ::1 my-debian-clone localhost6.localdomain6 localhost6"
  ln_is "## ::1 localhost ip6-localhost ip6-loopback"
  ln_is "## fe00::0 ip6-localnet"
  ln_is "## ff00::0 ip6-mcastprefix"
  ln_is "## ff02::1 ip6-allnodes"
  ln_is "## ff02::2 ip6-allrouters"
  ln_is "## ff02::3 ip6-allhosts"
  no_ln	
}
