#!/bin/bash

# === WELCOME ===
# 
# BLSS stands for Bootstrapped Linux Server Systems, it is set of tools to quickly 
# assemble multiple small & optimized Linux-based virtual appliances with the 
# purpose of an easy deployment of package-based distributed systems, like Apache 
# Hadoop Cloudera Distribution, where every server have a different role in a 
# computational cluster or grid. 
# 
# The delivered virtual appliances fit better for servicing purpose, they are 
# reduced in size and have a small memory footprint. The lifecycle of such systems 
# is composed of three phases: prototyping, where shared packages & configuration 
# is settled; cloning, where different server roles are defined; and finally 
# deployment where unique appliances are produced.
# 
# The project is hosted at https://bitbucket.org/eduardo_lago_aguilar/blss
# 
# === AUTHOR ===
#   Written by Eduardo Lago Aguilar, eduardo.lago.aguilar@gmail.com, 
#   http://eduardo-lago.blogspot.com

# it-clone-all:
#
#   Common ITs for all clones

# Changes context to the bootstrapped system prototype under test
ctx() {
  env -u LC_ALL LANG="nl_NL.UTF-8" LANGUAGE="nl_NL:nl" TZ="Europe/Amsterdam" sudo chroot /tmp/cloneitroot "$@"
}

# Test Case: Test for networking config
ctx cat /etc/network/interfaces | {
  ln_is "# The loopback network interface" "Verify if the loopback network interface is correct at /etc/network/interfaces"
  ln_is "auto lo" "Verify if lo automatically wakes up"
  ln_is "iface lo inet loopback" "Verify if lo defined as loopback"
  ln_is_empty
  ln_is "# The primary network interface" "Verify if the primary network interface eth0 is correct at /etc/network/interfaces"
  ln_is "auto eth0" "Verify if eth0 automatically wakes up"
  ln_is "iface eth0 inet static" "Verify if eth0 statically defined"
  ln_is "address 192.168.2.111" "Verify if correct address"
  ln_is "network 192.168.0.0" "Verify if correct network"
  ln_is "netmask 255.255.0.0" "Verify if correct netmask"
  ln_is "broadcast 192.168.255.255" "Verify if correct broadcast"
  ln_is "gateway 192.168.0.1" "Verify if correct gateway"
  ln_is "dns-nameservers 192.168.1.57" "Verify if dns-nameservers resolvconf option is correct at /etc/network/interfaces"
  ln_is "dns-search home.dev" "Verify if dns-search resolvconf option is correct at /etc/network/interfaces"
  no_ln
}

tst_pkg_installed() {
  ctx dpkg-query -W -f='${Status}' ${1:?} | awk '{print $NF}' | {
    ln_is "installed" "Verify if package ${1:?} is installed"
  }
}
tst_pkg_installed mc

