#!/bin/bash

# Integration Tests for prototype 'env/lennyi386'  

# Resolve script location, $0 may be a link
script="$0"
# Need this for relative symlinks
while [ -h "$script" ] ; do
  lst=$(ls -ld "$script")
  lnk=$(expr "$lst" : '.*-> \(.*\)$')
  if expr "$lnk" : '/.*' > /dev/null; then
    script="$lnk"
  else
    script=$(dirname "$script")/"$lnk"
  fi
done
BLSS_HOME=$(dirname "$script")/../..
BIN="$BLSS_HOME"/bin
ENV="$BLSS_HOME"/env
EXT="$BLSS_HOME"/ext
TST="$BLSS_HOME"/tst

. "$TST"/tst-commons

# Total amount of tests to perfom
plan_tests 6

# Test Case: Tests for size
DU=$(sudo du -hs /tmp/protoitroot)
DU=${DU%%M[[:space:]]*/tmp/protoitroot}
expected_sz=149
(( DU <= ${expected_sz} ))
ok $? "Verify is proto size $DU <= ${expected_sz}MB" 

. "$TST"/it-proto-all
. "$TST"/it-proto-debian
. "$TST"/it-proto-lenny

verify_adm_user_config
verify_static_networking\nverify_ip6_disabled

# Test Case: Tests for Kernel
ptx dpkg --get-selections linux-image* | awk '{print $1" "$2}' | {
  ln_is "linux-image-"$MJ.$MN.$RV-$RS"-686 install" "Verify if current Kernel is the correct Linux kernel image"
  ln_is "linux-image-686 install"
  no_ln "Verify if no other linux-image-* package is installed"
}
