#!/bin/bash

# Creates prototype 'env/lennyi386' if doesn't exists
# Creates clone 'env/lennyi386' using the prototype  
# Run ITs

# Resolve script location, $0 may be a link
script="$0"
# Need this for relative symlinks
while [ -h "$script" ] ; do
  lst=$(ls -ld "$script")
  lnk=$(expr "$lst" : '.*-> \(.*\)$')
  if expr "$lnk" : '/.*' > /dev/null; then
    script="$lnk"
  else
    script=$(dirname "$script")/"$lnk"
  fi
done
BLSS_HOME=$(dirname "$script")/../..
BIN="$BLSS_HOME"/bin
ENV="$BLSS_HOME"/env
EXT="$BLSS_HOME"/ext
TST="$BLSS_HOME"/tst

[ ! -e /tmp/protoitroot ] && sudo mkdir /tmp/protoitroot && $TST/lennyi386/proto
$TST/lennyi386/clone && $TST/lennyi386/it-clone
