#!/bin/bash
#
# WELCOME TO BLSS
#
# BLSS stands for Bootstrapped Linux-Server Systems, it's a collection of command line tools to
# quickly assemble, without user interaction, multiple small and optimized Linux-Server Systems
# with the purpose of an easy deployment of distributed systems, like Apache Hadoop Cloudera
# Distribution, where every Linux-Server may have a different role in the computational cluster or
# grid.
# With BLSS you can finally verify -with just one Enter key pressing- if your package-based
# system really works when you distribute it, and pay any technical debt you posses with
# yourself not accomplished yet because you don’t have the necessary time for install 10 or 100
# servers coordinating jobs in a network.
# Systems you manage with BLSS scripts fit better for servicing purpose, they are reduced
# in size and have a small memory footprint. The lifecycle of such systems is composed of
# three phases, each one with a corresponding script: prototyping with lxp, cloning with lxc and
# deployment with lxd.
#
# AUTHOR
#   Written by Eduardo Lago Aguilar, eduardo.lago.aguilar@gmail.com

# Integration Test Suite for proto natty.  
#
# Multiple calls to lxp can be very time consuming. Therefor several integration 
# tests are executed for a single proto. An integration test, for any proto, 
# assumes that the proto is located at '/tmp/protoitroot', so every verification is 
# performed on the filesystem hierarchy directly under '/tmp/protoitroot'.
# 
# Proto settings for Integration Tests are enviroments located under the 'env' 
# directory. The enviroment corresponding to the "protoA", for example, should 
# have the path $BLSS_HOME/env/A.
# 
# In the scope of Integration Tests, protos are named as 'proto' + one alphabet 
# letters from A..Z in uppercase or the name like natty. 

# Resolve script location, $0 may be a link
script="$0"
# Need this for relative symlinks
while [ -h "$script" ] ; do
  lst=$(ls -ld "$script")
  lnk=$(expr "$lst" : '.*-> \(.*\)$')
  if expr "$lnk" : '/.*' > /dev/null; then
    script="$lnk"
  else
    script=$(dirname "$script")/"$lnk"
  fi
done
BLSS_HOME=$(dirname "$script")/../..
BIN="$BLSS_HOME"/bin
ENV="$BLSS_HOME"/env
EXT="$BLSS_HOME"/ext
TST="$BLSS_HOME"/tst

. "$TST"/tst-commons

# Total amount of tests to perfom
plan_tests 7

# Test Case: Tests for size
DU=$(sudo du -hs /tmp/protoitroot)
DU=${DU%%M[[:space:]]*/tmp/protoitroot}
expected_sz=265
(( DU <= ${expected_sz} ))
ok $? "Verify is proto size $DU <= ${expected_sz}MB" 

. "$TST"/it-proto-all

verify_adm_user_config
verify_static_networking\nverify_ip6_disabled

# Test Case: Test for hostname config
ptx cat /etc/hostname | {
  ln_is "my-ubuntu-proto" "Verify if '/etc/hostname' is correct"
}

ptx cat /etc/hosts | {
  ln_is "127.0.0.1 localhost.localdomain localhost" "Verify if localhost is 127.0.0.1 at /etc/hosts"
  ln_is "127.0.1.1 my-ubuntu-proto my-ubuntu-proto.home.dev" "Verify if myserver and myserver.home.dev is 127.0.1.1 at /etc/hosts"
  ln_is_empty  
  ln_is "# The following lines are desirable for IPv6 capable hosts" "Verify if IPv6 capable hosts is commented"
  ln_is "## ::1 my-ubuntu-proto localhost6.localdomain6 localhost6"
  ln_is "## ::1 localhost ip6-localhost ip6-loopback"
  ln_is "## fe00::0 ip6-localnet"
  ln_is "## ff00::0 ip6-mcastprefix"
  ln_is "## ff02::1 ip6-allnodes"
  ln_is "## ff02::2 ip6-allrouters"
  ln_is "## ff02::3 ip6-allhosts"
  no_ln	
}

# Test Case: Tests for Kernel
ptx dpkg --get-selections linux-image\* | awk '{print $1" "$2}' | {
  ln_is "linux-image-"$MJ.$MN.$RV-$RS"-server install" "Verify if current Kernel is the Linux kernel image on Server Equipment"
  ln_is "linux-image-server install"
  no_ln "Verify if no other linux-image-* package is installed"
}

# Test Case: Test for ngetty
ptx egrep 'exec \/sbin\/getty -8 38400 tty1' /etc/init/tty1.conf | {
  ln_is "# exec /sbin/getty -8 38400 tty1"  "Verify if getty for tty1 is commented"
}
ptx egrep 'exec \/sbin\/ngetty 1 2 3 4 5 6' /etc/init/tty1.conf | {
  ln_is "exec /sbin/ngetty 1 2 3 4 5 6" "Verify if ngetty is configured for all ttys"
}
ptx egrep -v '^(#.*)?$' /etc/init/tty2.conf | {
  no_ln "Verify if getty for tty2 is commented"
}
ptx egrep -v '^(#.*)?$' /etc/init/tty3.conf | {
  no_ln "Verify if getty for tty3 is commented"
}
ptx egrep -v '^(#.*)?$' /etc/init/tty4.conf | {
  no_ln "Verify if getty for tty4 is commented"
}
ptx egrep -v '^(#.*)?$' /etc/init/tty5.conf | {
  no_ln "Verify if getty for tty5 is commented"
}
ptx egrep -v '^(#.*)?$' /etc/init/tty6.conf | {
  no_ln "Verify if getty for tty6 is commented"
}
