#!/bin/bash

# Integration Tests for deployment 'env/maverick'

# Resolve script location, $0 may be a link
script="$0"
# Need this for relative symlinks
while [ -h "$script" ] ; do
  lst=$(ls -ld "$script")
  lnk=$(expr "$lst" : '.*-> \(.*\)$')
  if expr "$lnk" : '/.*' > /dev/null; then
    script="$lnk"
  else
    script=$(dirname "$script")/"$lnk"
  fi
done
BLSS_HOME=$(dirname "$script")/../..
BIN="$BLSS_HOME"/bin
ENV="$BLSS_HOME"/env
EXT="$BLSS_HOME"/ext
TST="$BLSS_HOME"/tst

. "$TST"/tst-commons

# Total amount of tests to perfom
plan_tests 22

. "$TST"/it-dep-all

# Unbind devices on ERROR
trap _release_devs_on_err INT TERM EXIT

mount_img

. "$TST"/it-dep-ubuntu

[ -h /mnt/lib64 ] ; ok $? "Verify if link exists"

_release_devs

# No longer need to release devices on error
trap - INT TERM EXIT
