#!/bin/bash

# Clone creation 'env/squeezei386'

# Resolve script location, $0 may be a link
script="$0"
# Need this for relative symlinks
while [ -h "$script" ] ; do
  lst=$(ls -ld "$script")
  lnk=$(expr "$lst" : '.*-> \(.*\)$')
  if expr "$lnk" : '/.*' > /dev/null; then
    script="$lnk"
  else
    script=$(dirname "$script")/"$lnk"
  fi
done
BLSS_HOME=$(dirname "$script")/../..
BIN="$BLSS_HOME"/bin
ENV="$BLSS_HOME"/env
EXT="$BLSS_HOME"/ext
TST="$BLSS_HOME"/tst

sudo rm -rf /tmp/cloneitroot && \
BLSS_ENV="`realpath "$ENV"/squeezei386`" $BIN/lxc --proto-root /tmp/protoitroot --address 172.23.2.111 /tmp/cloneitroot
